config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#landing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home', to: 'pages#home'
  resources :games, only: [:show, :edit, :update] do
    resources :items, only: :create
    resource :settings, only: [:edit, :update]

    member do
      post 'start'
    end

    member do
      post 'result'
    end
  end

  resources :players, only: [:create, :new]

  patch '/games/:game_id/players/:id', to: 'players#update'

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @game = Game.find(params[:game_id])
    @player = current_player
  end

  def update
    @game = Game.find(params[:game_id])
    @player = current_player
    @player.update(color: params[:color])

    # Broadcoast
    @game.participations.each do |participation|
      ParticipationChannel.broadcast_to(
        participation,
        render_to_string(partial: "players/players",
          locals: { receiver_participation: participation },
          formats: [:html]
        )
      )
    end

    redirect_to edit_game_path(@game)
    # @participation = @game.participations.find_by(player: current_player)
    # @game.participations.update_all(role: 'ghost')

  end
end

app/views/settings/edit.html.erb
<div id="pages_settings_edit">
<div id="center-setting">
  <h1 id="setting_title">SETTINGS</h1>
</div>

<div class="colors-choice">
  <div id="pickup">
    <%= "Pick your" %> <br> <%= "favorite color" %>
  </div>

    <div class="colored_ghost">
      <div class="colors">
          <%= simple_form_for :player, url: game_settings_path(@game), method: :patch do |f| %>
        <div class="colors-ghost-choice">
            <% Game::COLORS.each do |color| %>
              <label class="">
                <%= radio_button_tag "color", color, current_player.color == color, hidden: true %>
                <%= image_tag "ghost_#{color}.png",
                class: "ghost" %>
              </label>
            <% end %>
        </div>
            <div class="d-flex justify-content-center">
              <%= image_tag "ghost_#{current_player.color ? current_player.color : 'red'}.png", class: "ghost_chosen" %>
            </div>
            <%= f.submit "CONFIRM", id: "confirm_color", class: "btn btn-ghost" %>
          <% end %>

      </div>
  </div>
</div>
<%# <p>add here a condition </p>
<p> if a player is ghost then </p>
<p> he can change the color of its ghost </p>
<p> if a player is pacman we cannot change its color. Pacman's color default: Yellow. </p> %>

<%# data-settings-target="icon" %>